CREATE SEQUENCE address_seq START WITH 1;
CREATE SEQUENCE dorms_seq START WITH 1;
CREATE SEQUENCE rooms_seq START WITH 1;
CREATE SEQUENCE position_seq START WITH 1;
CREATE SEQUENCE staff_seq START WITH 1;
CREATE SEQUENCE students_history_seq START WITH 1;
CREATE SEQUENCE furniture_seq START WITH 1;
CREATE SEQUENCE STUDENTS_SEQ minvalue 100000 maxvalue 999999;
