set serveroutput ON;
--SHOULD PRINT : STUDENT GENDER DOES NOT MATCH ROOM
EXEC ADD_STUDENT(100000, 'PAWEL', 'PROBNY', 7, 'M');

--SHOULD PRINT : ROOM IS FULL
EXEC ADD_STUDENT(100000, 'PAWEL', 'PROBNY', 4, 'M');

--SHOULD PRINT : STUDENT GENDER DOES NOT MATCH DORM
EXEC ADD_STUDENT(100000, 'PULINA', 'PROBNA', 1, 'F');

--SHOULD ADD STUDENT TO ROOM, CONFIMED WITH OUTPUT: STUDENT REGISTERED IN DORM SUCCESSFULLY
EXEC ADD_STUDENT(100000, 'PAWEL', 'PROBNY', 1, 'M');

--SHOULD DELETE STUDENT, CONFIMED WITH OUTPUT: STUDENT REMOVED SUCCESFULLY
EXEC DELETE_STUDENT(100000);

--SHOULD PRINT 'STUDENT DOES NOT EXIST'
EXEC DELETE_STUDENT(0);

--SHOULD PLACE STUDENT IN DORM (IF THERE IS A ROOM LEFT), CONFIRMED WITH: STUDENT REGISTERED IN DORM SUCCESSFULLY
EXEC ALOCATE_STUDENT_IN_DORM('Riviera', 100000, 'PAWEL', 'PROBNY', 'M')
EXEC DELETE_STUDENT(100000);

--SHOULD PRINT: DIDNT FIND ROOM FOR A STUDENT
EXEC ALOCATE_STUDENT_IN_DORM('Rumcajs', 100000, 'PAWEL', 'PROBNY', 'M')
